config/routes.rb
Rails.application.routes.draw do
  root 'assignations#index'
  put '/restart', to: 'assignations#restart'
  resources :assignations, only: [:index]
  resources :invitations, only: [:index, :new, :create]
  resources :users, only: [:index, :new]
  delete '/user/:id', to: 'users#delete', as: 'user' #for deleting user by admin to not confuse with devise destroy methods
  devise_for :users, controllers: {registrations: "users/registrations"}
  post '/add', to: 'users#add' #for adding user by admin
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GarbageLottery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/assignations.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lottery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- navbars -->
<body style="background-color: white" class="assignation">
  <% if current_user.admin==true %> <!-- diffrent nav bar for admin -->
  <div style="position: fixed">
    <ul class="pasek">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation") %> </li>
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li style="float: right; border-right: 3px solid #419873;"><%= link_to('Admin Panel', invitations_path) %></li>
    <li class="login"> You have signed in as,<span style="color: #419873;"> admin</span></li>
    </ul>
    <ul class="submenu">
      <li class="submenu"> <%= link_to("Restart", restart_path,method: :put, :class=>"submenu") %> </li>
      <li style="float: right; margin-right: 5%"><div style="color: #b62020; font-weight:bold; margin-top:5%">You have <%= Assignation.where(user_mail: current_user.email).size %> assignations this week. </div></li>
    </ul>
  </div>
  <%elsif current_user.admin==nil%> <!-- diffrent nav bar for user -->
    <ul class="pasek" style="margin-bottom: 5%">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation") %> </li>
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li class="login"> You have signed in as, <span style="color: #419873;">  <%= current_user.email %></span> </li>
  </ul>
  <ul class="submenu">
    <li style="float: right; margin-right: 5%"><div style="color: #b62020; font-weight:bold; margin-top:5%">You have <%= Assignation.where(user_mail: current_user.email).size %> assignations this week. </div></li>
  </ul>

  <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/invitations.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>Lottery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- navbars -->
<body style="background-color: white" class="invitation">
  <% if current_user.admin==true %> <!-- diffrent nav bar for admin -->
    <ul class="pasek">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation", style: "border-right: 3px solid #419873;") %> </li> <li class="pasek">
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li style="float: right; border-right: 3px solid #419873;"><%= link_to('Admin Panel', invitations_path, class: "admin" ) %></li>
    <li class="login"> You have signed in as,<span style="color: #419873;"> admin</span></li>
    </ul>
    <ul class="submenu" style="margin-left: 197px">
      <li class="submenu"> <%= link_to("List", invitations_path, :class=>"submenu") %><li class="submenu list"> <%= link_to("New", new_invitation_path, :class=>"submenu new_inv") %>
    </ul>
    <ul class="admin-menu">
      <li class="arrow_box" style="margin-top: 20%">  <%= link_to(invitations_path,class: "mail") do %>
      <%= image_tag("mail.png", height: '50', width: '50') %> <br>
      <span >  Invitations </span>
    <% end %></li>
    <li class="user">  <%= link_to(users_path,class: "mail") do %>
      <%= image_tag("users.png", height: '50', width: '50') %> <br>
      <span >  Users </span>
    <% end %></li>
    </ul>
  <%elsif current_user.admin==nil%> <!-- diffrent nav bar for user -->
    <ul class="pasek">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation") %> </li>
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li class="login"> You have signed in as, <span style="color: #419873;">  <%= current_user.email %></span> </li>
    </ul>

  <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lottery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- navbars -->
<body style="background-color: white" class="user">
  <% if current_user.admin==true %> <!-- diffrent nav bar for admin -->

  <ul class="pasek">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation", style: "border-right: 3px solid #419873;") %> </li> <li class="pasek">
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li style="float: right; border-right: 3px solid #419873;"><%= link_to('Admin Panel', invitations_path, class: "admin") %></li>
    <li class="login"> You have signed in as,<span style="color: #419873;"> admin</span></li>
  </ul>
  <ul class="submenu"  style="margin-left: 195px">
             <li class="submenu"> <%= link_to("List", users_path,:class=>"submenu") %> </li><li class="submenu"> <%= link_to("Add", new_user_path,:class=>"submenu") %> </li>
     </ul>
    <ul class="admin-menu">
    <li class="arrow_box" style="margin-top: 20%">  <%= link_to(invitations_path,class: "mail") do %>
      <%= image_tag("mail.png", height: '50', width: '50') %> <br>
      <span >  Invitations </span>
    <% end %></li>
    <li class="user">  <%= link_to(users_path,class: "mail") do %>
      <%= image_tag("users.png", height: '50', width: '50') %> <br>
      <span >  Users </span>
    <% end %></li>
    </ul>

  <%elsif current_user.admin==nil%> <!-- diffrent nav bar for user -->
    <ul class="pasek" style="margin-bottom: 5%">
    <li> <%= link_to("Schedule", assignations_path, :class => "assignation") %> </li>
    <li style="float: right;"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
    <li class="login"> You have signed in as, <span style="color: #419873;">  <%= current_user.email %></span> </li>
    </ul>

  <% end %>
<%= yield %>

</body>
</html>